### ISSUE TITLE
Menue item is collapsable which is not clickable on browser

### ISSUE THREAD

**Issue by msalmanshahid** [stepanenko3/nova-logs-tool#1]
Hello,
Thanks for the Nova4 support. I used this package when was updating to silver surfer. I am now using latest 1.1.5 and can see an issue that the menueSection is collapsable. Which is not clickable on browser. 

Can you please fix the issue or you can help me if i am missing something.

Many Thanks

**Comment by stepanenko3** [comment]
@msalmanshahid,
Thanks for your issue
I fix it in version [1.1.6](https://github.com/stepanenko3/nova-logs-tool/releases/tag/v1.1.6)
