### ISSUE TITLE
 Undefined array key 1

### ISSUE THREAD

**Issue by nw-mjl** [stepanenko3/nova-logs-tool#11]
[2022-08-29 11:44:34] local.ERROR: Undefined array key 1 {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /var/www/html/vendor/stepanenko3/laravel-log-viewer/src/Helpers/Log.php:48)

**Comment by stepanenko3** [comment]
Hi, @nw-mjl
Send your log file, pls

**Comment by hardcod3r** [comment]
Attempt to read property "name" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"name\" on null at /var/www/clients/client0/web1/web/vendor/stepanenko3/nova-logs-tool/src/Http/Controllers/LogsController.php:41)

if (!$file) {
            $file = $files->first()->name;
            //$files->first() is null
    }

**Comment by abordage** [comment]
@stepanenko3, this is the same as #6

**Comment by stepanenko3** [comment]
@hardcod3r @abordage @nw-mjl 
Fixed in https://github.com/stepanenko3/nova-logs-tool/releases/tag/v2.1.0
