### ISSUE TITLE
Attempt to read property "name" on null

### ISSUE THREAD

**Issue by Metilar** [stepanenko3/nova-logs-tool#13]
The error occurs immediately after deleting the log file.

`Attempt to read property "name" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"name\" on null at \\vendor\\stepanenko3\\nova-logs-tool\\src\\Http\\Controllers\\LogsController.php:42)`

**Comment by rafaelsmith** [comment]
Same here

**Comment by forgecodex** [comment]
Same here

**Comment by stepanenko3** [comment]
@Metilar @rafaelsmith @BeiAduo 
Fixed in https://github.com/stepanenko3/nova-logs-tool/releases/tag/v2.1.0
