### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by pavloniym** [stepanenko3/nova-logs-tool#15]
Can't update to laravel 10 because of ` stepanenko3/laravel-log-viewer` which is require `illuminate/contracts ^8.0|^9.0` (laravel 10 has `illuminate/contracts ^10`)

**Comment by stepanenko3** [comment]
@pavloniym 
Fixed in https://github.com/stepanenko3/nova-logs-tool/releases/tag/v2.1.0

**Comment by pavloniym** [comment]
@stepanenko3 
Thank you! Awesome package!

**Comment by stepanenko3** [comment]
> @stepanenko3 
> 
> Thank you! Awesome package!

Pleasant use 😉
