### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by alisalimik** [stepanenko3/nova-logs-tool#16]
when I click on tool shows 403 error page

**Comment by alisalimik** [comment]
<img width="1840" alt="Screenshot 2023-02-24 at 10 42 35 PM" src="https://user-images.githubusercontent.com/98024891/221270607-cf39c250-1d76-4470-9a23-6ada43d2ee5a.png">

**Comment by stepanenko3** [comment]
@alisalimik Send a screenshot of your NovaServiceProvider, please

It looks like you've restricted access to the resource

**Comment by stepanenko3** [comment]
@alisalimik Please reopen the issue if the problem is still relevant
