### ISSUE TITLE
cannot publish config

### ISSUE THREAD

**Issue by rabol** [stepanenko3/nova-logs-tool#17]
Hi

in the installation one is asked to publish the config

```
php artisan vendor:publish --provider="Stepanenko3\LogsTool\LogsToolServiceProvider"
```
however:

```
   INFO  No publishable resources for tag [].  
   ```

**Comment by danish-khan-I** [comment]
I am facing the same issue

**Comment by Ivankali2020** [comment]
same how to add resource on menu bar with MenuSection 

 MenuSection::resource(LogsTool::class)->icon('shopping-bag'), like this

**Comment by stepanenko3** [comment]
@rabol @danish-khan-I This package does not have a config file

Config in package `stepanenko3/laravel-log-viewer` try `php artisan vendor:publish --provider="Stepanenko3\LaravelLogViewer\LogViewerServiceProvider"`
