### ISSUE TITLE
"protected array $_mergedIndex" cannot be assigned null error

### ISSUE THREAD

**Issue by krisimmig** [stepanenko3/nova-logs-tool#20]
When loading the Logs page, I get the error:

`Cannot assign null to property Stepanenko3\LaravelLogViewer\Helpers\LogReader::$_mergedIndex of type array`. 

I can make it work when I change `/laravel-log-viewer/src/Helpers/LogReader.php:31`
```php
protected ?array $_mergedIndex;
```

I am using Laravel 10, Nova 4.33.0 and php 8.1

**Comment by stepanenko3** [comment]
HI, @krisimmig 
Fixed in https://github.com/stepanenko3/laravel-log-viewer/releases/tag/v1.3.2
