### ISSUE TITLE
All API routes are publicly exposed

### ISSUE THREAD

**Issue by WillyReyno** [stepanenko3/nova-logs-tool#25]
Hello, 

Just wanted to let you know that all API routes from your package are currently exposed even without access to Laravel Nova.

Meaning that even without being authenticated, any user could read or download logs (and probably delete) from the application as long as your package is installed. 

For example, just reaching `http://your-nova-app.com/nova-vendor/stepanenko3/logs-tool/logs?page=1` in a private web browser will show you the logs.

I think that can be pretty dangerous, as logs could expose sensitive data about the application and its structure.

**Comment by mdrbx** [comment]
Any news on this ? This is quite concerning.

**Comment by stepanenko3** [comment]
welcome to PR

**Comment by mdrbx** [comment]
After careful review of the claim it seems like LogsToolServiceProvider.php already add "nova" middleware which seems sufficient.

**Comment by mdrbx** [comment]
Sorry about the peer pressure mate 🙇

**Comment by stepanenko3** [comment]
Fixed in v2.2.3
