### ISSUE TITLE
Displaying latest log messages on a Nova dashboard (possible documentation addition?)

### ISSUE THREAD

**Issue by johnpuddephatt** [stepanenko3/nova-logs-tool#9]
I was looking into displaying log messages on my Nova dashboard using the new [Table metric](https://nova.laravel.com/docs/4.0/metrics/defining-metrics.html#table-metrics) introduced in V4.

I took a look at how this package gets data from logs and realised I could piggyback off it very easily!

Below is all that was needed to display the latest three lines from laravel.log (this is from the 'calculate' method of my table metric)

```
        $lines = array_slice(Stepanenko3\LogsTool\LogsService::all("laravel.log"), 0, 3);
        foreach ($lines as $line) {
            $rows[] = MetricTableRow::make()
                ->icon(
                    $line["level_img"]
                )
                ->iconClass(
                    $line["level_class"]
                )
                ->title($line["text"])
                ->subtitle(
                    \Carbon\Carbon::create($line["date"])->diffForHumans()
                );
        }
        return $rows;
    

```

and here's the result:

![Screenshot 2022-07-25 at 10 58 35](https://user-images.githubusercontent.com/8030910/180751169-1a012d1c-cb39-40e7-9bc0-a8fd9ee66f6f.jpg)

**Comment by stepanenko3** [comment]
@johnpuddephatt, thank you so much for your idea

I'll write it down to README a little later
Or you can open PR

**Comment by stepanenko3** [comment]
@johnpuddephatt, I added it to README

Thanks for the idea
